authentication:
  redirect_url: ${REDIRECT_URL}

spring:
  application:
    name: backend

# OAUTH2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email

  profiles:
    active: dev

# MINIO
minio:
  server:
    url: ${MINIO_SERVER_URL}
  access:
    key: ${MINIO_ROOT_USER}
  secret:
    key: ${MINIO_ROOT_PASSWORD}

  bucket:
    cv: cv-bucket
    avatar: avatar-bucket

# Internal
internal:
  cv-assessment:
    endpoint: /assess-cv

# Stripe
stripe:
  secret_key: ${STRIPE_SECRET_KEY}
  webhook_secret: ${STRIPE_WEBHOOK_SECRET}

# Mail
mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}