--
-- PostgreSQL database dump
--

\restrict ctyILUtpy1erhutZTDTa2RfRJxSi02OdR3YdatVCdSXBQfyc7Z9KX4UG8n3f4aF

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ai_interview_log; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.ai_interview_log (
    log_id bigint NOT NULL,
    ai_evaluation character varying(4096),
    content character varying(4096) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    role character varying(255) NOT NULL,
    session_id bigint NOT NULL,
    question_id bigint,
    CONSTRAINT ai_interview_log_role_check CHECK (((role)::text = ANY ((ARRAY['AI'::character varying, 'USER'::character varying])::text[])))
);


ALTER TABLE public.ai_interview_log OWNER TO quan;

--
-- Name: ai_interview_log_log_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public.ai_interview_log ALTER COLUMN log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_interview_log_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_interview_session; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.ai_interview_session (
    session_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    cv_url character varying(512),
    overall_feedback character varying(1024) NOT NULL,
    overall_score bigint NOT NULL,
    interviewee_id bigint NOT NULL,
    position_id bigint NOT NULL
);


ALTER TABLE public.ai_interview_session OWNER TO quan;

--
-- Name: ai_interview_session_session_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public.ai_interview_session ALTER COLUMN session_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_interview_session_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: answer_keyword; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.answer_keyword (
    keyword_id bigint NOT NULL,
    keyword character varying(50) NOT NULL,
    weight numeric(4,2) NOT NULL,
    question_id bigint NOT NULL
);


ALTER TABLE public.answer_keyword OWNER TO quan;

--
-- Name: answer_keyword_keyword_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public.answer_keyword ALTER COLUMN keyword_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.answer_keyword_keyword_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: available_schedule; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.available_schedule (
    schedule_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    day_of_week smallint NOT NULL,
    end_time time(0) without time zone,
    start_time time(0) without time zone,
    updated_at timestamp(6) without time zone NOT NULL,
    interviewer_id bigint NOT NULL,
    CONSTRAINT available_schedule_day_of_week_check CHECK (((day_of_week <= 8) AND (day_of_week >= 2)))
);


ALTER TABLE public.available_schedule OWNER TO quan;

--
-- Name: available_schedule_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public.available_schedule ALTER COLUMN schedule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.available_schedule_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blocked_schedule; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.blocked_schedule (
    blocked_schedule_id bigint NOT NULL,
    end_datetime timestamp(6) without time zone NOT NULL,
    note character varying(255),
    purpose character varying(255) NOT NULL,
    start_datetime timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    interviewer_id bigint NOT NULL,
    CONSTRAINT blocked_schedule_purpose_check CHECK (((purpose)::text = ANY ((ARRAY['INTERVIEW_BOOKED'::character varying, 'PERSONAL'::character varying])::text[])))
);


ALTER TABLE public.blocked_schedule OWNER TO quan;

--
-- Name: blocked_schedule_blocked_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public.blocked_schedule ALTER COLUMN blocked_schedule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blocked_schedule_blocked_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.booking (
    booking_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    cv_url character varying(255),
    end_time timestamp(6) without time zone NOT NULL,
    join_url character varying(255),
    meeting_id character varying(255),
    meeting_password character varying(255),
    payment_intent character varying(255),
    start_time timestamp(6) without time zone NOT NULL,
    start_url character varying(255),
    status character varying(255) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    booker_id bigint NOT NULL,
    interview_result_id bigint,
    interviewer_id bigint NOT NULL,
    position_id bigint,
    CONSTRAINT booking_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'IN_PROGRESS'::character varying, 'AWAIT_REVIEW'::character varying, 'PAID'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.booking OWNER TO quan;

--
-- Name: booking_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public.booking ALTER COLUMN booking_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking_review; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.booking_review (
    review_id bigint NOT NULL,
    comment character varying(512),
    created_at timestamp(6) without time zone NOT NULL,
    rating double precision,
    booking_id bigint NOT NULL
);


ALTER TABLE public.booking_review OWNER TO quan;

--
-- Name: booking_review_review_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public.booking_review ALTER COLUMN review_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_review_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.category (
    category_id bigint NOT NULL,
    category_name character varying(255) NOT NULL
);


ALTER TABLE public.category OWNER TO quan;

--
-- Name: category_category_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public.category ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cv_assessment; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.cv_assessment (
    assessment_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    cv_url character varying(2048),
    improvement_suggestion character varying(512) NOT NULL,
    layout_comment character varying(512) NOT NULL,
    match_comment character varying(512) NOT NULL,
    match_score bigint NOT NULL,
    overall_score bigint NOT NULL,
    interviewee_id bigint NOT NULL,
    position_id bigint NOT NULL
);


ALTER TABLE public.cv_assessment OWNER TO quan;

--
-- Name: cv_assessment_assessment_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public.cv_assessment ALTER COLUMN assessment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_assessment_assessment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cv_section_feedback; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.cv_section_feedback (
    feedback_id bigint NOT NULL,
    comment character varying(512) NOT NULL,
    score bigint NOT NULL,
    section_name smallint NOT NULL,
    assessment_id bigint NOT NULL,
    CONSTRAINT cv_section_feedback_section_name_check CHECK (((section_name >= 0) AND (section_name <= 4)))
);


ALTER TABLE public.cv_section_feedback OWNER TO quan;

--
-- Name: cv_section_feedback_feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public.cv_section_feedback ALTER COLUMN feedback_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_section_feedback_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interviewee; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.interviewee (
    interviewee_id bigint NOT NULL,
    subscription_expired_date date,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.interviewee OWNER TO quan;

--
-- Name: interviewer; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.interviewer (
    interviewer_id bigint NOT NULL,
    is_stripe_connected boolean,
    overall_rating double precision,
    stripe_id character varying(255),
    total_reviews integer,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.interviewer OWNER TO quan;

--
-- Name: interviewer_expertise; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.interviewer_expertise (
    cv_url character varying(2048),
    experience_year integer,
    hourly_fee numeric(5,2),
    is_certified boolean,
    level character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    interviewer_id bigint NOT NULL,
    position_id bigint NOT NULL,
    CONSTRAINT interviewer_expertise_level_check CHECK (((level)::text = ANY ((ARRAY['INTERN'::character varying, 'FRESHER'::character varying, 'JUNIOR'::character varying, 'SENIOR'::character varying])::text[])))
);


ALTER TABLE public.interviewer_expertise OWNER TO quan;

--
-- Name: inteview_result; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.inteview_result (
    result_id bigint NOT NULL,
    communication_score bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    overall_comment character varying(512) NOT NULL,
    preparation_level character varying(255) NOT NULL,
    technical_score bigint NOT NULL,
    CONSTRAINT inteview_result_preparation_level_check CHECK (((preparation_level)::text = ANY ((ARRAY['WELL_PREPARED'::character varying, 'MODERATE'::character varying, 'UNDER_PREPARED'::character varying])::text[])))
);


ALTER TABLE public.inteview_result OWNER TO quan;

--
-- Name: inteview_result_result_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public.inteview_result ALTER COLUMN result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inteview_result_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.payment (
    payment_id bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    currency character varying(255) NOT NULL,
    failure_message character varying(255),
    receipt_url character varying(255),
    status character varying(255) NOT NULL,
    stripe_charge_id character varying(255),
    booking_id bigint NOT NULL,
    stripe_payment_intent_id character varying(255) NOT NULL,
    CONSTRAINT payment_currency_check CHECK (((currency)::text = ANY ((ARRAY['USD'::character varying, 'VND'::character varying])::text[]))),
    CONSTRAINT payment_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'AUTHORIZED'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying])::text[])))
);


ALTER TABLE public.payment OWNER TO quan;

--
-- Name: payment_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public.payment ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: position; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public."position" (
    position_id bigint NOT NULL,
    position_name character varying(100) NOT NULL
);


ALTER TABLE public."position" OWNER TO quan;

--
-- Name: position_position_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public."position" ALTER COLUMN position_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.position_position_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: position_question; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.position_question (
    is_required boolean NOT NULL,
    position_id bigint NOT NULL,
    question_id bigint NOT NULL
);


ALTER TABLE public.position_question OWNER TO quan;

--
-- Name: question; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.question (
    question_id bigint NOT NULL,
    content character varying(500) NOT NULL,
    difficulty_level character varying(255) NOT NULL,
    suggestion_answer character varying(2048) NOT NULL,
    CONSTRAINT question_difficulty_level_check CHECK (((difficulty_level)::text = ANY ((ARRAY['EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying])::text[])))
);


ALTER TABLE public.question OWNER TO quan;

--
-- Name: question_category; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.question_category (
    question_id bigint NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public.question_category OWNER TO quan;

--
-- Name: question_question_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public.question ALTER COLUMN question_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_account; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.social_account (
    social_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    provider character varying(255) NOT NULL,
    provider_id character varying(255) NOT NULL,
    user_id bigint,
    CONSTRAINT social_account_provider_check CHECK (((provider)::text = ANY ((ARRAY['GOOGLE'::character varying, 'GITHUB'::character varying])::text[])))
);


ALTER TABLE public.social_account OWNER TO quan;

--
-- Name: social_account_social_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public.social_account ALTER COLUMN social_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_account_social_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: quan
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    avatar character varying(2048),
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(150),
    github_url character varying(512),
    is_enabled boolean DEFAULT false NOT NULL,
    linkedin_url character varying(512),
    role character varying(255) NOT NULL,
    user_name character varying(50),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['Interviewer'::character varying, 'Interviewee'::character varying, 'Admin'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO quan;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: quan
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: ai_interview_log; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.ai_interview_log (log_id, ai_evaluation, content, created_at, role, session_id, question_id) FROM stdin;
\.


--
-- Data for Name: ai_interview_session; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.ai_interview_session (session_id, created_at, cv_url, overall_feedback, overall_score, interviewee_id, position_id) FROM stdin;
\.


--
-- Data for Name: answer_keyword; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.answer_keyword (keyword_id, keyword, weight, question_id) FROM stdin;
1	doing	1.00	1
2	Deming cycle	1.00	1
3	planning	1.00	1
4	acting	1.00	1
5	Plan Do Check Act	1.00	1
6	continuous improvement	1.00	1
7	checking	1.00	1
8	PDCA	1.00	1
9	Quality Assurance	1.00	2
10	preventing defects	1.00	2
11	find and fix defects	1.00	2
12	Testing	1.00	2
13	product-oriented	1.00	2
14	process-oriented	1.00	2
15	process management	1.00	2
16	methods	1.00	3
17	scope of testing	1.00	3
18	Test Strategy	1.00	3
19	testing objectives	1.00	3
20	document	1.00	3
21	resources	1.00	3
22	testing approach	1.00	3
23	schedule	1.00	3
24	Test Plan	1.00	3
25	version of software	1.00	4
26	ready for testing	1.00	4
27	finalized application	1.00	4
28	Release	1.00	4
29	delivered to customers	1.00	4
30	Build	1.00	4
31	defect	1.00	5
32	accepted	1.00	5
33	Bug Leakage	1.00	5
34	Bug Release	1.00	5
35	knowingly containing defects	1.00	5
36	found by end-users	1.00	5
37	Traceability Matrix	1.00	6
38	test cases	1.00	6
39	document	1.00	6
40	validated	1.00	6
41	links requirements	1.00	6
42	requirements covered	1.00	6
43	missed during testing	1.00	7
44	effectiveness	1.00	7
45	escape into production	1.00	7
46	Defect Leakage Ratio	1.00	7
47	percentage of defects	1.00	7
48	after development	1.00	8
49	QC	1.00	8
50	identifying defects	1.00	8
51	systematic process	1.00	8
52	preventing defects	1.00	8
53	QA	1.00	8
54	quality processes	1.00	8
55	unexpected conditions	1.00	9
56	random inputs	1.00	9
57	Monkey testing	1.00	9
58	without predefined test cases	1.00	9
59	behavior	1.00	9
60	specific module	1.00	10
61	Gorilla testing	1.00	10
62	exhaustively	1.00	10
63	functionality without bugs	1.00	10
64	significant number of test cases	1.00	10
65	random inputs	1.00	11
66	Monkey testing	1.00	11
67	without defined test cases	1.00	11
68	specific module	1.00	11
69	intensive testing	1.00	11
70	entire application	1.00	11
71	Gorilla testing	1.00	11
72	test scripts	1.00	12
73	documentation	1.00	12
74	Testware	1.00	12
75	testing process	1.00	12
76	artifacts	1.00	12
77	test cases	1.00	12
78	data files	1.00	12
79	covered by test cases	1.00	13
80	Test Coverage Matrix	1.00	13
81	requirements adequately tested	1.00	13
82	Requirement Traceability Matrix	1.00	13
83	minimizing gaps	1.00	13
84	Data Driven Testing	1.00	14
85	stored separately	1.00	14
86	multiple tests	1.00	14
87	test scripts	1.00	14
88	test data	1.00	14
89	different data sets	1.00	14
90	expected user load	1.00	15
91	stress testing	1.00	15
92	Load testing	1.00	15
93	performance	1.00	15
94	behavior	1.00	15
95	extreme conditions	1.00	15
96	beyond capacity	1.00	15
97	functional requirements	1.00	16
98	usability	1.00	16
99	reliability	1.00	16
100	non-functional testing	1.00	16
101	attributes	1.00	16
102	Functional testing	1.00	16
103	performance	1.00	16
104	without internal structures	1.00	17
105	functionality	1.00	17
106	internal logic	1.00	17
107	white box testing	1.00	17
108	structure of the code	1.00	17
109	Black box testing	1.00	17
110	ensuring end product quality	1.00	18
111	controlling processes	1.00	18
112	Quality Assurance	1.00	18
113	Quality Control	1.00	18
114	fulfill quality requirements	1.00	18
115	computing as a service	1.00	19
116	hardware	1.00	19
117	end-user	1.00	19
118	business management user	1.00	19
119	services	1.00	19
120	cloud	1.00	19
121	networks	1.00	19
122	storage	1.00	19
123	cloud service provider	1.00	19
124	files	1.00	20
125	datasets	1.00	20
126	objects	1.00	20
127	Cloud storage levels	1.00	20
128	blocks	1.00	20
129	technical interface	1.00	20
130	storage device	1.00	20
131	infrastructure	1.00	21
132	services	1.00	21
133	cloud computing architecture	1.00	21
134	middleware	1.00	21
135	components	1.00	21
136	applications	1.00	21
137	commercial vendors	1.00	22
138	Cloud service providers	1.00	22
139	cloud consumers	1.00	22
140	companies	1.00	22
141	selling services	1.00	22
142	create and manage capabilities	1.00	22
143	underlying cloud technology	1.00	23
144	benefit from services	1.00	23
145	without awareness	1.00	23
146	Direct customers	1.00	23
147	interacting directly	1.00	23
148	constituents	1.00	24
149	cloud ecosystem	1.00	24
150	cloud service providers	1.00	24
151	cloud consumers	1.00	24
152	direct customers	1.00	24
153	multi-cloud	1.00	25
154	deployment	1.00	25
155	private cloud	1.00	25
156	operational needs	1.00	25
157	versions of the cloud	1.00	25
158	hybrid cloud	1.00	25
159	public cloud	1.00	25
160	IaaS	1.00	26
161	PaaS	1.00	26
162	Cloud delivery models	1.00	26
163	FaaS	1.00	26
164	Platform as a Service	1.00	26
165	computing environments	1.00	26
166	Infrastructure as a Service	1.00	26
167	SaaS	1.00	26
168	Software as a Service	1.00	26
169	Function as a Service	1.00	26
170	multi-tenancy	1.00	27
171	agility	1.00	27
172	key features	1.00	27
173	reliability	1.00	27
174	scalability	1.00	27
175	location independence	1.00	27
176	dependencies	1.00	28
177	run consistently	1.00	28
178	different environments	1.00	28
179	Encapsulation	1.00	28
180	without compatibility issues	1.00	28
181	packaging software code	1.00	28
182	network traffic	1.00	29
183	restrict	1.00	29
184	protect against API overuse	1.00	29
185	Rate Limiting	1.00	29
186	eliminate malicious activities	1.00	29
187	authentication	1.00	30
188	rate limiting	1.00	30
189	API gateway	1.00	30
190	intermediary for API calls	1.00	30
191	managing multiple APIs	1.00	30
192	server	1.00	30
193	uniform experience	1.00	30
194	Edge computing	1.00	31
195	IoT scenarios	1.00	31
196	reducing latency	1.00	31
197	data generation	1.00	31
198	bandwidth use	1.00	31
199	near the source	1.00	31
200	processing data close to origin	1.00	31
201	optimized performance	1.00	32
202	dynamic orchestration	1.00	32
203	microservices	1.00	32
204	leverage cloud computing benefits	1.00	32
205	Cloud-native applications	1.00	32
206	containers	1.00	32
207	web technology	1.00	33
208	multitenant technology	1.00	33
209	broadband networks	1.00	33
210	service technology	1.00	33
211	Cloud-enabling technologies	1.00	33
212	data center technology	1.00	33
213	virtualization technology	1.00	33
214	reference point	1.00	34
215	regulate project weaknesses	1.00	34
216	software development milestone	1.00	34
217	completion	1.00	34
218	decrease vulnerability	1.00	34
219	software deliverables	1.00	34
220	baseline	1.00	34
221	adding new features	1.00	35
222	better and more efficient	1.00	35
223	functionalities	1.00	35
224	Software Re-engineering	1.00	35
225	updating software	1.00	35
226	Verification	1.00	36
227	meets required standards	1.00	36
228	accomplishes objectives without defects	1.00	36
229	quality criteria	1.00	36
230	Validation	1.00	36
231	analysis tools	1.00	37
232	design tools	1.00	37
233	database management tools	1.00	37
234	automate SDLC tasks	1.00	37
235	CASE tools	1.00	37
236	project management tools	1.00	37
237	software application programs	1.00	37
238	user needs	1.00	38
239	system requirements specifications	1.00	38
240	SRS	1.00	38
241	representation of software	1.00	38
242	formal report	1.00	38
243	networking	1.00	39
244	system software	1.00	39
245	embedded software	1.00	39
246	categories of software	1.00	39
247	artificial intelligence software	1.00	39
248	scientific software	1.00	39
249	web development software	1.00	39
250	complicated	1.00	40
251	high costs	1.00	40
252	not recommended for small projects	1.00	40
253	high skill level	1.00	40
254	reliance on risk analysis	1.00	40
255	drawbacks of the spiral model	1.00	40
256	Proof of Concept	1.00	41
257	POC	1.00	41
258	validate an idea	1.00	41
259	limited functionality	1.00	41
260	working model	1.00	41
261	practicality	1.00	41
262	Software prototyping	1.00	41
263	parallel development	1.00	42
264	deliver iterations faster	1.00	42
265	identify risks on a module basis	1.00	42
266	facilitates user feedback	1.00	42
267	merits of the incremental model	1.00	42
268	reduces initial delivery costs	1.00	42
269	explicitly defining	1.00	43
270	activities involved	1.00	43
271	Software scope	1.00	43
272	developing and delivering	1.00	43
273	well-defined boundary	1.00	43
274	well-defined requirements	1.00	44
275	waterfall method	1.00	44
276	short projects	1.00	44
277	linear SDLC approach	1.00	44
278	unchangeable requirements	1.00	44
279	finished sequentially	1.00	44
280	set of instructions	1.00	45
281	computer software	1.00	45
282	collection of multiple programs	1.00	45
283	computer program	1.00	45
284	programming language	1.00	45
285	complete tasks	1.00	45
286	expectations	1.00	46
287	structure	1.00	46
288	leads and manages	1.00	46
289	goals	1.00	46
290	software product manager	1.00	46
291	overseeing specialization	1.00	46
292	software product management department	1.00	46
293	enhance production	1.00	47
294	codes	1.00	47
295	minimizing mistakes	1.00	47
296	SCM	1.00	47
297	systematically manages changes	1.00	47
298	documents	1.00	47
299	Software Configuration Management	1.00	47
300	separate independent modules	1.00	48
301	simpler program management	1.00	48
302	Modularity	1.00	48
303	breaking down functionality	1.00	48
304	developed and maintained independently	1.00	48
305	finding and resolving bugs	1.00	49
306	Debugging	1.00	49
307	ensuring software runs correctly	1.00	49
308	identifying and correcting problems	1.00	49
309	modularization	1.00	50
310	specific functionalities	1.00	50
311	easier to develop and maintain	1.00	50
312	self-contained components	1.00	50
313	designing applications	1.00	50
314	analyze performance	1.00	51
315	quantitative measures	1.00	51
316	estimate productivity	1.00	51
317	stress testing	1.00	51
318	load testing	1.00	51
319	program properties	1.00	51
320	Software Metrics	1.00	51
\.


--
-- Data for Name: available_schedule; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.available_schedule (schedule_id, created_at, day_of_week, end_time, start_time, updated_at, interviewer_id) FROM stdin;
\.


--
-- Data for Name: blocked_schedule; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.blocked_schedule (blocked_schedule_id, end_datetime, note, purpose, start_datetime, updated_at, interviewer_id) FROM stdin;
\.


--
-- Data for Name: booking; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.booking (booking_id, created_at, cv_url, end_time, join_url, meeting_id, meeting_password, payment_intent, start_time, start_url, status, total_amount, updated_at, booker_id, interview_result_id, interviewer_id, position_id) FROM stdin;
\.


--
-- Data for Name: booking_review; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.booking_review (review_id, comment, created_at, rating, booking_id) FROM stdin;
\.


--
-- Data for Name: category; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.category (category_id, category_name) FROM stdin;
\.


--
-- Data for Name: cv_assessment; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.cv_assessment (assessment_id, created_at, cv_url, improvement_suggestion, layout_comment, match_comment, match_score, overall_score, interviewee_id, position_id) FROM stdin;
\.


--
-- Data for Name: cv_section_feedback; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.cv_section_feedback (feedback_id, comment, score, section_name, assessment_id) FROM stdin;
\.


--
-- Data for Name: interviewee; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.interviewee (interviewee_id, subscription_expired_date, updated_at) FROM stdin;
2	2026-08-31	2026-08-01 22:06:27.008016
\.


--
-- Data for Name: interviewer; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.interviewer (interviewer_id, is_stripe_connected, overall_rating, stripe_id, total_reviews, updated_at) FROM stdin;
3	t	4	acct_1TwyL2JJyijhpJey	5	2026-08-01 22:06:27.034083
\.


--
-- Data for Name: interviewer_expertise; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.interviewer_expertise (cv_url, experience_year, hourly_fee, is_certified, level, updated_at, interviewer_id, position_id) FROM stdin;
\N	1	5.00	t	FRESHER	2026-08-01 22:28:09.752716	3	1
\N	1	5.00	t	FRESHER	2026-08-01 22:28:09.770425	3	2
\N	1	5.00	t	FRESHER	2026-08-01 22:28:09.771949	3	3
\.


--
-- Data for Name: inteview_result; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.inteview_result (result_id, communication_score, created_at, overall_comment, preparation_level, technical_score) FROM stdin;
\.


--
-- Data for Name: payment; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.payment (payment_id, amount, created_at, currency, failure_message, receipt_url, status, stripe_charge_id, booking_id, stripe_payment_intent_id) FROM stdin;
\.


--
-- Data for Name: position; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public."position" (position_id, position_name) FROM stdin;
1	quality assurance
2	software engineer
3	cloud computing
\.


--
-- Data for Name: position_question; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.position_question (is_required, position_id, question_id) FROM stdin;
f	1	1
f	2	1
f	1	2
f	2	2
f	1	3
f	2	3
f	1	4
f	2	4
f	1	5
f	2	5
f	1	6
f	2	6
f	1	7
f	2	7
f	1	8
f	2	8
f	1	9
f	2	9
f	1	10
f	2	10
f	1	11
f	2	11
f	1	12
f	1	13
f	2	13
f	1	14
f	2	14
f	1	15
f	2	15
f	3	15
f	1	16
f	2	16
f	1	17
f	2	17
f	1	18
f	2	18
f	3	19
f	2	19
f	3	20
f	3	21
f	2	21
f	3	22
f	3	23
f	3	24
f	3	25
f	2	25
f	3	26
f	2	26
f	3	27
f	3	28
f	2	28
f	3	29
f	2	29
f	1	29
f	3	30
f	2	30
f	3	31
f	2	31
f	3	32
f	2	32
f	3	33
f	2	34
f	1	34
f	2	35
f	1	36
f	2	36
f	2	37
f	2	38
f	1	38
f	2	39
f	2	40
f	2	41
f	2	42
f	2	43
f	2	44
f	2	45
f	2	46
f	2	47
f	1	47
f	2	48
f	2	49
f	1	49
f	2	50
f	1	51
f	2	51
\.


--
-- Data for Name: question; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.question (question_id, content, difficulty_level, suggestion_answer) FROM stdin;
1	What is the lifecycle of a Quality Assurance Process?	EASY	Every process in Quality Assurance involves the PDCA (Plan Do Check Act) cycle, also known as the Deming cycle, consisting of planning, doing, checking, and acting to ensure continuous improvement of processes.
2	Differentiate between Quality Assurance and Testing.	EASY	Quality Assurance (QA) is process-oriented and focuses on preventing defects through process management, while Testing is product-oriented and aims to find and fix defects that are present in the product.
3	Differentiate between Test Plan and Test Strategy.	EASY	A Test Plan is a document that describes the testing approach, resources, schedule, and the scope of testing. A Test Strategy outlines the testing objectives and methods to be used during the project.
4	What do you mean by build and release in the context of quality assurance?	EASY	Build refers to a version of software ready for testing, while Release is the finalized application delivered to customers after development and testing.
5	What do you understand about bug leakage and bug release?	EASY	Bug Leakage occurs when a defect that should have been identified during testing is found by end-users. Bug Release refers to a version of the software released knowingly containing defects that are accepted for various reasons.
6	What do you understand about Traceability Matrix (TM) in the context of quality assurance?	EASY	A Traceability Matrix is a document that links requirements to test cases ensuring that all requirements are covered and validated in the software testing process.
7	What do you understand about defect leakage ratio in the context of quality assurance?	EASY	Defect Leakage Ratio measures the percentage of defects that escape into production after being missed during the testing phase, indicating the effectiveness of the testing process.
8	Differentiate between Quality Assurance (QA) and Quality Control (QC).	EASY	QA is a systematic process that focuses on preventing defects by ensuring quality processes, whereas QC is about identifying defects in the products after they have been developed.
9	What do you mean by monkey testing in the context of quality assurance?	EASY	Monkey testing is a type of software testing where random inputs are provided to the application without predefined test cases to check its behavior under unexpected conditions.
10	What do you mean by gorilla testing in the context of quality assurance?	EASY	Gorilla testing is a software testing technique focused on testing a specific module exhaustively with a significant number of test cases to ensure its functionality without bugs.
11	Differentiate between gorilla testing and monkey testing.	EASY	Gorilla testing focuses on intensive testing of a specific module, while Monkey testing involves testing the entire application with random inputs without defined test cases.
12	Explain what is a testware in the context of quality assurance.	EASY	Testware refers to all the artifacts created during the testing process, including test cases, test scripts, data files, and other documentation that helps in executing tests.
13	How would you ensure that your testing is thorough and comprehensive?	EASY	Utilizing the Requirement Traceability Matrix and Test Coverage Matrix helps to ensure all requirements are adequately tested and covered by test cases, minimizing gaps.
14	What do you understand about data driven testing?	EASY	Data Driven Testing is a testing methodology where test data is stored separately from the test scripts, allowing multiple tests to be executed with different data sets efficiently.
15	What do you understand about load testing and stress testing?	HARD	Load testing assesses the application's performance under expected user load, while stress testing evaluates the system’s behavior under extreme conditions beyond its capacity.
16	Differentiate between functional and non-functional testing.	HARD	Functional testing verifies that the application meets functional requirements, while non-functional testing assesses attributes like performance, usability, and reliability.
17	What do you understand about black box and white box testing?	HARD	Black box testing evaluates the functionality without looking into internal structures, while white box testing focuses on the internal logic and structure of the code.
18	What is the difference between Quality Assurance and Quality Control?	HARD	Quality Assurance focuses on ensuring that the end product will be of the requested quality, while Quality Control focuses on controlling processes used in development to fulfill quality requirements.
19	What is a Cloud Technology?	EASY	A cloud is a combination of services, networks, hardware, storage, and interfaces that helps in delivering computing as a service. It broadly has three users: the end-user, business management user, and cloud service provider.
20	What are the Cloud Storage Levels?	EASY	Cloud storage levels include files, blocks, datasets, and objects, each associated with a specific technical interface corresponding to the cloud storage device used.
21	Describe the Cloud Computing Architecture.	EASY	The cloud computing architecture comprises all components of a cloud model that fit together from an architectural perspective, including applications, middleware, infrastructure, and services associated with cloud services.
22	Who are the Cloud service providers in a cloud ecosystem?	EASY	Cloud service providers are the commercial vendors or companies that create and manage their own capabilities, selling their services to cloud consumers or providing services internally.
23	Who are the Direct customers in a cloud ecosystem?	EASY	Direct customers are users who benefit from services created within a cloud environment, interacting directly with those services without awareness of the underlying cloud technology.
24	What are the main constituents that are part of the cloud ecosystem?	EASY	The main constituents of the cloud ecosystem include cloud consumers, direct customers, and cloud service providers.
25	What are the different versions of the cloud?	EASY	The different versions of the cloud include public cloud, private cloud, hybrid cloud, and multi-cloud, each serving different deployment and operational needs.
26	What do you mean by cloud delivery models?	EASY	Cloud delivery models represent the computing environments, including Infrastructure as a Service (IaaS), Platform as a Service (PaaS), Software as a Service (SaaS), and Function as a Service (FaaS).
27	What are some of the key features of Cloud Computing?	EASY	Key features of cloud computing include agility, location independence, multi-tenancy, reliability, and scalability.
28	What do you mean by encapsulation in cloud computing?	EASY	Encapsulation in cloud computing refers to packaging software code with all its dependencies so it can run consistently across different environments without compatibility issues.
29	What do you mean by Rate Limiting?	EASY	Rate Limiting is a method to restrict the amount of network traffic, helping to eliminate malicious activities and protect against API overuse.
30	What is an API Gateway?	EASY	An API gateway is a server that acts as an intermediary for API calls, managing multiple APIs and providing a uniform experience while handling tasks like authentication and rate limiting.
31	What is meant by Edge Computing?	HARD	Edge computing refers to computing that takes place at or near the source of data generation, reducing latency and bandwidth use by processing data close to its origin, often used in IoT scenarios.
32	What are Cloud-Native Applications?	HARD	Cloud-native applications are designed to leverage cloud computing benefits, utilizing containers, microservices, and dynamic orchestration for optimized performance and development.
33	What are cloud-enabling technologies?	HARD	Cloud-enabling technologies include broadband networks, data center technology, virtualization technology, web technology, multitenant technology, and service technology that support cloud infrastructures.
34	What is baseline in Software Development?	EASY	A baseline is a software development milestone and reference point marked by the completion or delivery of one or more software deliverables. The main objective of the baseline is to decrease and regulate vulnerability, or project weaknesses that can easily damage the project and lead to uncontrollable changes.
35	What do you mean by Software Re-engineering?	EASY	The process of updating software is known as software reengineering. This procedure entails adding new features and functionalities to the software in order to make it better and more efficient.
36	What are Verification and Validation?	EASY	Verification is the process of ensuring that software accomplishes its objectives without defects. Validation is the process of determining whether a software product meets the required standards, or in other words, whether it meets the product's quality criteria.
37	What are CASE tools?	EASY	CASE tools are a collection of software application programs that automate SDLC tasks. They include analysis tools, design tools, project management tools, database management tools, and documentation tools to simplify various stages of the Software Development Life Cycle.
38	What is SRS?	EASY	SRS is a formal report that serves as a representation of software that allows customers to assess whether it meets their needs. It includes user needs for a system and precise system requirements specifications.
39	What are the various categories of software?	EASY	Software products are mainly categorized into system software, networking and web development software, embedded software, artificial intelligence software, and scientific software.
40	What are the drawbacks of the spiral model?	EASY	The spiral model is significantly more complicated than other SDLC models. It is not recommended for small projects due to high costs and a reliance on risk analysis that necessitates a high skill level.
41	What is Software prototyping and POC?	EASY	A software prototype is a working model with limited functionality. POC (Proof of Concept) is a method used to validate an idea or concept's practicality before starting the software development process.
42	What are the merits of the incremental model?	EASY	The incremental model can deliver iterations faster, allows parallel development, reduces initial delivery costs, facilitates user feedback, and helps identify risks on a module basis.
43	What is Software scope?	EASY	The scope of a software project is a well-defined boundary that incorporates all the activities involved in developing and delivering a software product, explicitly defining what the final product will and will not include.
44	What is the waterfall method and what are its use cases?	EASY	The waterfall model is a linear SDLC approach where each step is finished sequentially. It's suitable for well-defined and unchangeable requirements, short projects, and when technology is well understood.
45	What is the main difference between a computer program and computer software?	EASY	A computer program is a set of instructions expressed in a programming language, while software is a collection of multiple programs used to complete tasks.
46	What does a software product manager do?	EASY	A software product manager leads and manages the software product management department, overseeing the specialization, goals, structure, and expectations of the software product.
47	What is Software Configuration Management?	HARD	Software Configuration Management (SCM) systematically manages changes in documents, codes, and other entities during the Software Development Life Cycle to enhance production while minimizing mistakes.
48	What is Modularity?	HARD	Modularity is the practice of breaking down a program's functionality into separate, independent modules which can be developed and maintained independently, leading to simpler program management.
49	What is Debugging?	HARD	Debugging is the process of finding and resolving bugs in software, ensuring the software runs correctly after identifying and correcting problems.
50	Explain the concept of modularization.	HARD	Modularization is the practice of designing applications as self-contained components with specific functionalities to make them easier to develop and maintain.
51	What are Software Metrics?	HARD	Software metrics are quantitative measures of program properties used to analyze performance, plan, estimate productivity, and include metrics like load testing and stress testing.
\.


--
-- Data for Name: question_category; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.question_category (question_id, category_id) FROM stdin;
\.


--
-- Data for Name: social_account; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.social_account (social_id, created_at, provider, provider_id, user_id) FROM stdin;
1	2026-08-01 22:06:26.882534	GOOGLE	113635588445946844380	1
2	2026-08-01 22:06:27.000153	GOOGLE	116906374507955881320	2
3	2026-08-01 22:06:27.024744	GOOGLE	118345548882952024278	3
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: quan
--

COPY public.users (user_id, avatar, created_at, email, full_name, github_url, is_enabled, linkedin_url, role, user_name) FROM stdin;
1	\N	2026-08-01 22:06:26.862535	ngocquan612006@gmail.com	Trần Ngọc Quân	\N	t	\N	Admin	Quanbroisdead
2	\N	2026-08-01 22:06:26.998687	downloadvpn612006@gmail.com	Trần Ngọc downloadvpn	\N	t	\N	Interviewee	downloadvpn
3	\N	2026-08-01 22:06:27.022873	quanbro7612006@gmail.com	Trần Ngọc Bro	\N	t	\N	Interviewer	quanbro7
\.


--
-- Name: ai_interview_log_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.ai_interview_log_log_id_seq', 1, false);


--
-- Name: ai_interview_session_session_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.ai_interview_session_session_id_seq', 1, false);


--
-- Name: answer_keyword_keyword_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.answer_keyword_keyword_id_seq', 320, true);


--
-- Name: available_schedule_schedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.available_schedule_schedule_id_seq', 1, false);


--
-- Name: blocked_schedule_blocked_schedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.blocked_schedule_blocked_schedule_id_seq', 1, false);


--
-- Name: booking_booking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.booking_booking_id_seq', 1, false);


--
-- Name: booking_review_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.booking_review_review_id_seq', 1, false);


--
-- Name: category_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.category_category_id_seq', 1, false);


--
-- Name: cv_assessment_assessment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.cv_assessment_assessment_id_seq', 1, false);


--
-- Name: cv_section_feedback_feedback_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.cv_section_feedback_feedback_id_seq', 1, false);


--
-- Name: inteview_result_result_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.inteview_result_result_id_seq', 1, false);


--
-- Name: payment_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.payment_payment_id_seq', 1, false);


--
-- Name: position_position_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.position_position_id_seq', 3, true);


--
-- Name: question_question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.question_question_id_seq', 51, true);


--
-- Name: social_account_social_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.social_account_social_id_seq', 3, true);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quan
--

SELECT pg_catalog.setval('public.users_user_id_seq', 3, true);


--
-- Name: ai_interview_log ai_interview_log_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.ai_interview_log
    ADD CONSTRAINT ai_interview_log_pkey PRIMARY KEY (log_id);


--
-- Name: ai_interview_session ai_interview_session_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.ai_interview_session
    ADD CONSTRAINT ai_interview_session_pkey PRIMARY KEY (session_id);


--
-- Name: answer_keyword answer_keyword_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.answer_keyword
    ADD CONSTRAINT answer_keyword_pkey PRIMARY KEY (keyword_id);


--
-- Name: available_schedule available_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.available_schedule
    ADD CONSTRAINT available_schedule_pkey PRIMARY KEY (schedule_id);


--
-- Name: blocked_schedule blocked_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.blocked_schedule
    ADD CONSTRAINT blocked_schedule_pkey PRIMARY KEY (blocked_schedule_id);


--
-- Name: booking booking_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT booking_pkey PRIMARY KEY (booking_id);


--
-- Name: booking_review booking_review_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.booking_review
    ADD CONSTRAINT booking_review_pkey PRIMARY KEY (review_id);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (category_id);


--
-- Name: cv_assessment cv_assessment_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.cv_assessment
    ADD CONSTRAINT cv_assessment_pkey PRIMARY KEY (assessment_id);


--
-- Name: cv_section_feedback cv_section_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.cv_section_feedback
    ADD CONSTRAINT cv_section_feedback_pkey PRIMARY KEY (feedback_id);


--
-- Name: category idx_category_name; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT idx_category_name UNIQUE (category_name);


--
-- Name: position idx_position_name; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public."position"
    ADD CONSTRAINT idx_position_name UNIQUE (position_name);


--
-- Name: interviewee interviewee_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.interviewee
    ADD CONSTRAINT interviewee_pkey PRIMARY KEY (interviewee_id);


--
-- Name: interviewer_expertise interviewer_expertise_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.interviewer_expertise
    ADD CONSTRAINT interviewer_expertise_pkey PRIMARY KEY (interviewer_id, position_id);


--
-- Name: interviewer interviewer_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.interviewer
    ADD CONSTRAINT interviewer_pkey PRIMARY KEY (interviewer_id);


--
-- Name: inteview_result inteview_result_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.inteview_result
    ADD CONSTRAINT inteview_result_pkey PRIMARY KEY (result_id);


--
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (payment_id);


--
-- Name: position position_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public."position"
    ADD CONSTRAINT position_pkey PRIMARY KEY (position_id);


--
-- Name: position_question position_question_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.position_question
    ADD CONSTRAINT position_question_pkey PRIMARY KEY (position_id, question_id);


--
-- Name: question_category question_category_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.question_category
    ADD CONSTRAINT question_category_pkey PRIMARY KEY (question_id, category_id);


--
-- Name: question question_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_pkey PRIMARY KEY (question_id);


--
-- Name: social_account social_account_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.social_account
    ADD CONSTRAINT social_account_pkey PRIMARY KEY (social_id);


--
-- Name: booking uk26x1oh584vcnbb9lfw5q16dha; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT uk26x1oh584vcnbb9lfw5q16dha UNIQUE (position_id);


--
-- Name: booking uk5k1455ifru3c1e7ttgj212yug; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT uk5k1455ifru3c1e7ttgj212yug UNIQUE (interview_result_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: ai_interview_log ukiovnsrtcjv9q61k05ekjbuss4; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.ai_interview_log
    ADD CONSTRAINT ukiovnsrtcjv9q61k05ekjbuss4 UNIQUE (question_id);


--
-- Name: ai_interview_session ukjehrgy2i7xh8ojishkn24qpb8; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.ai_interview_session
    ADD CONSTRAINT ukjehrgy2i7xh8ojishkn24qpb8 UNIQUE (position_id);


--
-- Name: booking_review ukp4ps590fybk1a6a07kydp51h; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.booking_review
    ADD CONSTRAINT ukp4ps590fybk1a6a07kydp51h UNIQUE (booking_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: booking fk12mllnncxdnsqghakmb5mr1y; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fk12mllnncxdnsqghakmb5mr1y FOREIGN KEY (position_id) REFERENCES public."position"(position_id);


--
-- Name: booking fk1kljhtcwmprrglj8upwn3um93; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fk1kljhtcwmprrglj8upwn3um93 FOREIGN KEY (interview_result_id) REFERENCES public.inteview_result(result_id);


--
-- Name: interviewer fk1v219bt3uxfe4vui0xw8s96gq; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.interviewer
    ADD CONSTRAINT fk1v219bt3uxfe4vui0xw8s96gq FOREIGN KEY (interviewer_id) REFERENCES public.users(user_id);


--
-- Name: position_question fk3thlxrgp6khj40qftohstfkhd; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.position_question
    ADD CONSTRAINT fk3thlxrgp6khj40qftohstfkhd FOREIGN KEY (question_id) REFERENCES public.question(question_id);


--
-- Name: booking fk4bb37prhu2ikyyupierroj3jb; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fk4bb37prhu2ikyyupierroj3jb FOREIGN KEY (booker_id) REFERENCES public.interviewee(interviewee_id);


--
-- Name: booking fk5yq0gc2ni3lq5nxerdkh1do4t; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fk5yq0gc2ni3lq5nxerdkh1do4t FOREIGN KEY (interviewer_id) REFERENCES public.interviewer(interviewer_id);


--
-- Name: cv_section_feedback fk6kniwcryc15vkk01lifvy6g2n; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.cv_section_feedback
    ADD CONSTRAINT fk6kniwcryc15vkk01lifvy6g2n FOREIGN KEY (assessment_id) REFERENCES public.cv_assessment(assessment_id);


--
-- Name: cv_assessment fk7jvfe9grgqx51wev1kc9xltxr; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.cv_assessment
    ADD CONSTRAINT fk7jvfe9grgqx51wev1kc9xltxr FOREIGN KEY (position_id) REFERENCES public."position"(position_id);


--
-- Name: ai_interview_session fk82du164enj971pulg8cx088sb; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.ai_interview_session
    ADD CONSTRAINT fk82du164enj971pulg8cx088sb FOREIGN KEY (position_id) REFERENCES public."position"(position_id);


--
-- Name: question_category fk8am7a16ooqygccfeff0csl6ed; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.question_category
    ADD CONSTRAINT fk8am7a16ooqygccfeff0csl6ed FOREIGN KEY (category_id) REFERENCES public.category(category_id);


--
-- Name: blocked_schedule fk8ujp8ocrnuv8cu62m9owtmkvi; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.blocked_schedule
    ADD CONSTRAINT fk8ujp8ocrnuv8cu62m9owtmkvi FOREIGN KEY (interviewer_id) REFERENCES public.interviewer(interviewer_id);


--
-- Name: ai_interview_log fkc2n27gcowvub6wx3rwq8jcv8r; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.ai_interview_log
    ADD CONSTRAINT fkc2n27gcowvub6wx3rwq8jcv8r FOREIGN KEY (question_id) REFERENCES public.question(question_id);


--
-- Name: interviewee fkckfv66u6dt40ylky1v05b4gwi; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.interviewee
    ADD CONSTRAINT fkckfv66u6dt40ylky1v05b4gwi FOREIGN KEY (interviewee_id) REFERENCES public.users(user_id);


--
-- Name: ai_interview_log fkdl0nnry6awr0u0sttqgrswlg6; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.ai_interview_log
    ADD CONSTRAINT fkdl0nnry6awr0u0sttqgrswlg6 FOREIGN KEY (session_id) REFERENCES public.ai_interview_session(session_id);


--
-- Name: ai_interview_session fkdmvj5r037dmkixui87pysi9xr; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.ai_interview_session
    ADD CONSTRAINT fkdmvj5r037dmkixui87pysi9xr FOREIGN KEY (interviewee_id) REFERENCES public.interviewee(interviewee_id);


--
-- Name: answer_keyword fkfctihycns59h04t0ti8g4xiqr; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.answer_keyword
    ADD CONSTRAINT fkfctihycns59h04t0ti8g4xiqr FOREIGN KEY (question_id) REFERENCES public.question(question_id);


--
-- Name: position_question fkg7fvk9e0uwpyrwj78s3vehhe; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.position_question
    ADD CONSTRAINT fkg7fvk9e0uwpyrwj78s3vehhe FOREIGN KEY (position_id) REFERENCES public."position"(position_id);


--
-- Name: interviewer_expertise fkia5nhpive2w8cr6y2wk9b9ogf; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.interviewer_expertise
    ADD CONSTRAINT fkia5nhpive2w8cr6y2wk9b9ogf FOREIGN KEY (interviewer_id) REFERENCES public.interviewer(interviewer_id);


--
-- Name: interviewer_expertise fkj5ctutdxcxi4cw3qcvq9dlepq; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.interviewer_expertise
    ADD CONSTRAINT fkj5ctutdxcxi4cw3qcvq9dlepq FOREIGN KEY (position_id) REFERENCES public."position"(position_id);


--
-- Name: booking_review fkjkq7o59og4g3162nfq8kehrep; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.booking_review
    ADD CONSTRAINT fkjkq7o59og4g3162nfq8kehrep FOREIGN KEY (booking_id) REFERENCES public.booking(booking_id);


--
-- Name: cv_assessment fkl70vsfrtwrdvnmpotacuc8n5q; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.cv_assessment
    ADD CONSTRAINT fkl70vsfrtwrdvnmpotacuc8n5q FOREIGN KEY (interviewee_id) REFERENCES public.interviewee(interviewee_id);


--
-- Name: payment fkqewrl4xrv9eiad6eab3aoja65; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fkqewrl4xrv9eiad6eab3aoja65 FOREIGN KEY (booking_id) REFERENCES public.booking(booking_id);


--
-- Name: social_account fkqg7naq00cg9s76a2tljlyafn6; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.social_account
    ADD CONSTRAINT fkqg7naq00cg9s76a2tljlyafn6 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: available_schedule fkset0n5xx7x5kn74bchm7a5fmb; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.available_schedule
    ADD CONSTRAINT fkset0n5xx7x5kn74bchm7a5fmb FOREIGN KEY (interviewer_id) REFERENCES public.interviewer(interviewer_id);


--
-- Name: question_category fktd86c15n034sh16lgpcucfm6p; Type: FK CONSTRAINT; Schema: public; Owner: quan
--

ALTER TABLE ONLY public.question_category
    ADD CONSTRAINT fktd86c15n034sh16lgpcucfm6p FOREIGN KEY (question_id) REFERENCES public.question(question_id);


--
-- PostgreSQL database dump complete
--

\unrestrict ctyILUtpy1erhutZTDTa2RfRJxSi02OdR3YdatVCdSXBQfyc7Z9KX4UG8n3f4aF

